# Generated by Django 2.1.3 on 2018-11-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('inventory_type', models.CharField(choices=[(0, 'Сервер'), (1, 'Простой АРМ'), (2, 'Ноутбук')], max_length=24)),
                ('inventory_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Inventory')),
            ],
        ),
    ]
