# Generated by Django 2.1.3 on 2018-11-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.IntegerField(choices=[(0, 'Сервер'), (1, 'Простой АРМ'), (2, 'Ноутбук')], max_length=24),
        ),
    ]
